- Linux From Scratch (LFS) : https://www.linuxfromscratch.org/lfs/downloads/stable/
- Arch Linux Wiki : https://wiki.archlinux.org/
- Arch Linux image on DockerHub : https://gitlab.archlinux.org/archlinux/archlinux-docker
- Docker documentation : https://docs.docker.com/
