FROM archlinux:latest

# RUN pacman -Syu

RUN pacman -Sy binutils
RUN pacman -Sy bison
RUN pacman -Sy diffutils
RUN pacman -Sy gcc
RUN pacman -Sy m4
RUN pacman -Sy make
RUN pacman -Sy patch
RUN pacman -Sy perl
RUN pacman -Sy python
RUN pacman -Sy texinfo

VOLUME ~/Documents/CosmOS/
WORKDIR ~/Documents/CosmOS/
